### ISSUE TITLE
Spell checking does not work

### ISSUE THREAD

**Issue by c3er** [bartosz-antosik/vscode-spellright#138]
Spell checking does not work currently. I use this extension since months and worked always fine. Maybe the last update of Spell Right and/or VS Code have a cause.

- VS Code 1.22.1 (ia32)
- Spell Right 2.2.8
- Windows 8.1 64 bit (Version 6.3)

edit:

I use spell checking for Markdown files (that does currently not work).

**Comment by bartosz-antosik** [comment]
Could you please open Developer Tools (Help -> Toggle Developer) Tools and see if there (Console pane) is anything related to Spell Right?

**Comment by c3er** [comment]
The extension cannot be activated, because of an exception:

```
[Extension Host] Activating extension `ban.spellright` failed:  Cannot read property 'replace' of undefined
t.log @ /C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:260
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:260 [Extension Host] Here is the error stack:  TypeError: Cannot read property 'replace' of undefined
	at C:\Users\Test User\.vscode\extensions\ban.spellright-2.2.8\src\spellright.js:1839:37
	at Array.forEach (native)
	at SpellRightIndicator.updateStatusBarIndicator (C:\Users\Test User\.vscode\extensions\ban.spellright-2.2.8\src\spellright.js:1836:22)
	at new SpellRightIndicatorController (C:\Users\Test User\.vscode\extensions\ban.spellright-2.2.8\src\spellright.js:1911:34)
	at SpellRight.activate (C:\Users\Test User\.vscode\extensions\ban.spellright-2.2.8\src\spellright.js:99:22)
	at activate (C:\Users\Test User\.vscode\extensions\ban.spellright-2.2.8\src\extension.js:34:16)
	at Function.t._callActivateOptional (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:677:587)
	at Function.t._callActivate (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:677:271)
	at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:676:336
	at Object.g [as _notify] (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:69:572)
	at Object.enter (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:72:924)
	at n.Class.derive._oncancel._run (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:74:719)
	at n.Class.derive._oncancel._completed (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:74:160)
	at c (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:77:654)
	at q.then.o.(anonymous function) (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:77:868)
	at Object.g [as _notify] (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:69:572)
	at Object.enter (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:72:924)
	at n.Class.derive._oncancel._run (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:74:719)
	at n.Class.derive._oncancel._completed (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:74:160)
	at c (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:77:654)
	at q.then.o.(anonymous function) (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:77:868)
	at Object.g [as _notify] (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:69:572)
	at Object.enter (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:72:924)
	at n.Class.derive._oncancel._run (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:74:719)
	at n.Class.derive._oncancel._completed (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:74:160)
	at e.resolveOk (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:497:926)
	at e._receiveReply (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:559:735)
	at e._receiveOneMessage (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:559:79)
	at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:558:75
	at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:560:929
	at c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:88:30
	at e.fire (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:89:344)
	at Socket.<anonymous> (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:143:1008)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at Pipe.onread (net.js:560:20)
/C:/Program Files (x86)/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:260 [Extension Host] vscode-icons is active!
```

Additionally a screenshot:

![Console log of VS Code](https://user-images.githubusercontent.com/24460532/38554551-4cd8a9ba-3cc3-11e8-9799-c2a7c4f73c0a.png)

**Comment by bartosz-antosik** [comment]
Could you please show me your user/workspace configuaration regarding Spell Right? That is entries starting with "spellright"?

**Comment by c3er** [comment]
Since yesterday I tried VS Code with Spell Right on my Windows 10 machine at home and there it works fine (Windows 10 64 bit, same Versions of VS Code and Spell Right). There, I have only English (US) and German (Germany).

On my Windows 8.1 machine, I seem to have got almost every language available.

Here the snippet of my user settings:

```json
"spellright.language": "English",
"spellright.latexSpellParameters": [
  "title",
  "date",
  "author",
  "caption",
  "section",
  "subsection",
  "subsubsection",
  "paragraph",
  "subparagraph"
],
```

Here a full list of the installed languages:

- Arabic
- Bulgarian
- Catalan
- Chinese (Simplified) Legacy
- Czech
- Danish
- German
- Greek
- English
- Spanish
- Finnish
- French
- Hebrew
- Hungarian
- Icelandic
- Italian
- Japanese
- Korean
- Dutch
- Norwegian
- Polish
- Portuguese
- Romansh
- Romanian
- Russian
- Croatian
- Slovak
- Albanian
- Swedish
- Thai
- Turkish
- Urdu
- Indonesian
- Ukrainian
- Belarusian
- Slovenian
- Estonian
- Latvian
- Lithuanian
- Tajik
- Persian
- Vietnamese
- Armenian
- Azerbaijani
- Basque
- Upper Sorbian
- Macedonian (FYROM)
- Southern Sotho
- Tsonga
- Setswana
- isiXhosa
- isiZulu
- Afrikaans
- Georgian
- Faroese
- Hindi
- Maltese
- Sami (Northern)
- Irish
- Malay
- Kazakh
- Kyrgyz
- Kiswahili
- Turkmen
- Uzbek
- Tatar
- Bangla
- Punjabi
- Gujarati
- Odia
- Tamil
- Telugu
- Kannada
- Malayalam
- Assamese
- Marathi
- Sanskrit
- Mongolian
- Tibetan
- Welsh
- Khmer
- Lao
- Burmese
- Galician
- Konkani
- Sindhi
- Syriac
- Sinhala
- Cherokee
- Inuktitut
- Amharic
- Tamazight
- Nepali
- Frisian
- Pashto
- Filipino
- Divehi
- Fulah
- Hausa
- Yoruba
- Quechua
- Sesotho sa Leboa
- Bashkir
- Luxembourgish
- Greenlandic
- Igbo
- Oromo
- Tigrinya
- Guarani
- Hawaiian
- Somali
- Yi
- Mapudungun
- Mohawk
- Breton
- Invariant Language (Invariant Country)
- Uyghur
- Maori
- Occitan
- Corsican
- Alsatian
- Sakha
- K'iche
- Kinyarwanda
- Wolof
- Scottish Gaelic
- Central Kurdish

**Comment by bartosz-antosik** [comment]
Hi, this should be fixed in just published version 2.2.10. Please drop me a line whether it works for you!

**Comment by c3er** [comment]
Unfortunately not. I get still the same error (as it seems).

![Screenshot](https://user-images.githubusercontent.com/24460532/38684540-3839e132-3e70-11e8-9ddc-18fd095c50c5.png)

**Comment by bartosz-antosik** [comment]
Should eventually be OK in version 2.2.12. Sorry for the trouble. The situation you have (multiple languages) was hard to simulate precisely.

**Comment by c3er** [comment]
Works now. Thank you very much!

I was just googling for downgrading the extension to let you know, which version was the last working one.

**Comment by bartosz-antosik** [comment]
Oh, sorry for additional work. I know which version caused this - the one that allowed LANGUAGE-REGION separator characters mixed ("_" & "-")., that is version 2.2.8. Problem with recent version was just typo.

**Comment by c3er** [comment]
No problem. I was curious.

**Comment by PCDSandwichMan** [comment]
I am having the same issue. Would you mind letting me know which last working version your installed and how? I would really like to do the same.

Thank you

**Comment by c3er** [comment]
@PCDSandwichMan

It is long ago since I encountered this bug. At my systems, the spell checker works perfect currently.

I guess the last working version before that was 2.2.6. To install any version, go to the extensions view (Ctrl+Shift+X), right click on the "Spell Right" entry and choose "Install Another Version". A list appears, where you can choose the version to try out.

**Comment by mcnesium** [comment]
I am facing "command … not found" with VSCode OSS v1.33.1 and Spell Right v3.0.38 on Linux.

![Screenshot from 2019-05-22 13-43-35](https://user-images.githubusercontent.com/476060/58172019-b334d200-7c97-11e9-92ce-c66eb48d1907.png)

@PCDSandwichMan were you able to do something about it with another version?

**Comment by derpda** [comment]
Facing the same issue on vscode 1.35.1 with spellright 3.0.38 on Arch Linux 5.1.9-arch1-1-ARCH.
hunspell dictionaries linked to `$HOME/.config/Code\ -\ OSS/Dictionaries` (the package uses that folder...).
Also linked `$HOME/.config/Code\ -\ OSS` to `$HOME/.config/Code` to be safe.
